### PR TITLE
Add test script for CI server to run

### PR DESCRIPTION
**Pull request by OYTIS**

### CODE REVIEW

**Comment by OYTIS** [comment]
test

**Comment by OYTIS** [comment]
#hedwig start

**Comment by OYTIS** [comment]
**Hedwig** :owl: : starting a job.
                         ID `a286f3bc-e3ad-41d2-8533-e5b2099c6276`

**Comment by OYTIS** [comment]
**Hedwig** said YES.
        Get log at https://9784a26a.ngrok.io//jobs/a286f3bc-e3ad-41d2-8533-e5b2099c6276/log
        Restart by posting `#hedwig restart`

**Comment by OYTIS** [comment]
For `testscript.sh` - yes, absolutely. The idea was it to be a first naive iteration of what could later become `Hedwigfile`, hence the name without extension. But we can add it, it won't hurt.

For `modems.csv`, it is meant as the list of modems that _must_ be tested in order for CI to pass, hence it shouldn't depend on the CI machine. What can go wrong on a different locale?

**Comment by rbeiter** [comment]
The R211 is the European version of the HAT, we use the R203 in the US.

https://github.com/twilio/Breakout_Trust_Onboard_SDK/blob/master/tests/modems.csv#L2

**Comment by OYTIS** [comment]
Oh _that_ locale. That's a good point.

Actually I hoped to keep connectivity out of scope as long as we can, and test the applet and it's integration with various library. We can't connect to anywhere with a card reader for instance :)

So I think it won't hurt to just add R203 to the list and test it on the same machine as everything else (which is an RPi next to my desk for now).

**Comment by rbeiter** [comment]
When I tried the script last week, if a module is in that list and not found the runner fails.  Is that changed in this PR?

**Comment by OYTIS** [comment]
No, that's the expected behavior. The idea is that for each CI run we want to test all hardware modules we're interested in. We can do it without them connecting to MNOs, the ToB applet works fully offline.
So what we should do IMO, is to get you LARA-R211 and/or get me LARA-R203 and have them both on the list.

**Comment by OYTIS** [comment]
**Hedwig** :owl: : starting a job.
                         ID `957c1817-8717-4ed5-bc48-ca69b9731181`

**Comment by OYTIS** [comment]
**Hedwig** said YES.
        Get log at https://9784a26a.ngrok.io/jobs/957c1817-8717-4ed5-bc48-ca69b9731181/log
        Restart by posting `#hedwig restart`

**Comment by rbeiter** [comment]
This LGTM! :+1:

**Pull request merged**
