### PR TITLE
Add Azure IoT C samples using the signing key

### PR DESCRIPTION
**Pull request by OYTIS**
Adapted from the samples in azure-iot-sdk-c

### CODE REVIEW

**Comment by OYTIS** [comment]
**Hedwig** :owl: : starting a job.
                         ID `5db024c6-db34-46a2-9689-a58d684f4c7a`

**Comment by OYTIS** [comment]
**Hedwig** said NO.
        (Maybe) get log at https://708563bb.ngrok.io/jobs/5db024c6-db34-46a2-9689-a58d684f4c7a/log
        Restart by posting `#hedwig restart`

**Comment by OYTIS** [comment]
#hedwig restart

Server configuration error

**Comment by OYTIS** [comment]
**Hedwig** :owl: : starting a job.
                         ID `02f313b7-f5f1-4829-9529-f532f2bab972`

**Comment by OYTIS** [comment]
**Hedwig** said YES.
        Get log at https://708563bb.ngrok.io/jobs/02f313b7-f5f1-4829-9529-f532f2bab972/log
        Restart by posting `#hedwig restart`

**Comment by rbeiter** [comment]
What setup is required to compile this sample?

**Comment by OYTIS** [comment]
**Hedwig** :owl: : starting a job.
                         ID `2a6e514b-1aea-4a22-bb98-6cdff7845084`

**Comment by OYTIS** [comment]
@rbeiter Based on https://github.com/twilio/Breakout_Trust_Onboard_SDK/pull/35 now, only the last commit is for this PR.

One sample is left now. It was simplified, but I've added an extra commit to https://github.com/twilio/azure-iot-sdk-c, you need to update this one.

**Comment by OYTIS** [comment]
**Hedwig** :owl: : starting a job.
                         ID `4ba48184-cf9b-4772-9c68-291eef09dbe5`

**Comment by OYTIS** [comment]
Let's see how hedwig handles two parallel builds.

**Comment by OYTIS** [comment]
**Hedwig** said NO.
        (Maybe) get log at https://hedwig-tob-berlin.eu.ngrok.io/jobs/4ba48184-cf9b-4772-9c68-291eef09dbe5/log
        Restart by posting `#hedwig restart`

**Comment by OYTIS** [comment]
Of course it doesn't, they are fighting over the same set of devices.

**Comment by OYTIS** [comment]
**Hedwig** said NO.
        (Maybe) get log at https://hedwig-tob-berlin.eu.ngrok.io/jobs/2a6e514b-1aea-4a22-bb98-6cdff7845084/log
        Restart by posting `#hedwig restart`

**Comment by OYTIS** [comment]
**Hedwig** :owl: : starting a job.
                         ID `9bd5f17f-2d62-4291-9a57-a77bbdcef9eb`

**Comment by OYTIS** [comment]
**Hedwig** said YES.
        Get log at https://hedwig-tob-berlin.eu.ngrok.io/jobs/9bd5f17f-2d62-4291-9a57-a77bbdcef9eb/log
        Restart by posting `#hedwig restart`

**Comment by OYTIS** [comment]
**Hedwig** :owl: : starting a job.
                         ID `f72615e4-60e7-4729-94da-852435fc8058`

**Comment by rbeiter** [comment]
#hedwig restart

**Comment by OYTIS** [comment]
**Hedwig** said YES.
        Get log at https://hedwig-tob-berlin.eu.ngrok.io/jobs/f72615e4-60e7-4729-94da-852435fc8058/log
        Restart by posting `#hedwig restart`

**Pull request merged**
